Add setVirtualEnvFromFile function (#51)
* Add setVirtualEnvFromFile function to set up virtual environment from file requirements

* Improve setVirtualEnvFromFile function

* Update ProactiveTask.py

Fixed self.logger.info(f'Temporary file created and will be deleted: {temp_file_path}')
SyntaxError: invalid syntax

* Fixed syntax error for old python versions

---------

Co-authored-by: Andrews Cordolino Sobral <andrewssobral@users.noreply.github.com>
(cherry picked from commit ccafa921b80410cc17c746093703c605d7f8a691)